# Stellar TOML for NexLab
NETWORK_PASSPHRASE="Test SDF Network ; September 2015"

[[CURRENCIES]]
code="XLM"
issuer="GBJ2HOYPB2YJDKJ5RCALOZ3N4HKXQAQYVXBHV5LAWVE4NTVAUM2JJUZW"

[DOCUMENTATION]
ORG_NAME="NexLab"
ORG_URL="https://thong442001.github.io"